version: "3"

# FROM DOCKER DOCUMENTATION:
# By default Compose sets up a single network for your app.
# Each container for a service joins the default network and is both reachable by other containers on that network,
# and discoverable by them at a hostname identical to the container name.

services:
  cloud-server:
    build:
      context: "./server"
    # image: "limcollintj/eopsi-client"
    ports:
      - "5001:5001"
    volumes:
      - "./server:/app"
    # The AWS t2 micro instance can allow up to 1 GB of ram. Be careful when increasing mem limit
    mem_limit: 500m
